language: android
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_53b7518c7470_key -iv $encrypted_53b7518c7470_iv
  -in hiprock.jks.enc -out ./android/app/hiprock.jks -d
- openssl aes-256-cbc -K $encrypted_53b7518c7470_key -iv $encrypted_53b7518c7470_iv
  -in hocHipRock.mobileprovision.enc -out ./ios/RockCer/hocHipRock.mobileprovision
  -d
- openssl aes-256-cbc -K $encrypted_53b7518c7470_key -iv $encrypted_53b7518c7470_iv
  -in ios_distribution.cer.enc -out ./ios/RockCer/ios_distribution.cer -d
- openssl aes-256-cbc -K $encrypted_53b7518c7470_key -iv $encrypted_53b7518c7470_iv
  -in privateKey.p12.enc -out ./ios/RockCer/privateKey.p12 -d
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
cache:
  directories:
  - node_modules
script:
- cd android && ./gradlew clean
- "./gradlew assembleRelease"
- cd ./app/build/outputs/apk
- ls
- curl -F 'file=@app-internal-release-5.1.10.apk' -F 'uKey=24af41e3b5e5117e773a733378aefa29'
  -F '_api_key=0691c7489e57a5158796f6e1e7e988bd' -F 'password=rock' -F 'installType=2'
  -F 'updateDescription=5.1.10 test' 'https://qiniu-storage.pgyer.com/apiv1/app/upload'
- curl -F 'file=@app-prod-release-5.1.10.apk' -F 'uKey=24af41e3b5e5117e773a733378aefa29'
  -F '_api_key=0691c7489e57a5158796f6e1e7e988bd' -F 'password=rock' -F 'installType=2'
  -F 'updateDescription=5.1.10 prod' 'https://qiniu-storage.pgyer.com/apiv1/app/upload'
