language: objective-c
sudo: required
#xcode_project: ios/HipRock.xcodeproj # path to your xcodeproj folder
#xcode_scheme: Rock_Test
install: #1.2
#  - rmdir node_modules
  - npm install
#cache:
# directories:
#  - node_modules
script:
  - cd ios
  - xctool -project HipRock.xcodeproj -scheme Rock_Test clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
